-- Syntax Highlighting Plugins
return {
  {
    'nvim-treesitter/nvim-treesitter',
    build = ":TSUpdate",
    event = { "VeryLazy" },
    cmd = { "TSUpdateSync", "TSUpdate", "TSInstall" },
    branch = "main",

    config = function()
      require('nvim-treesitter').setup({})
      require('nvim-treesitter').install {
        "bash",
        "diff",
        "dockerfile",
        "dot",
        "fish",
        "git_rebase",
        "gitattributes",
        "gitcommit",
        "gitignore",
        "go",
        "gomod",
        "gosum",
        "helm",
        "html",
        "http",
        "ini",
        "java",
        "javascript",
        "jq",
        "json",
        "json5",
        "lua",
        "make",
        "markdown",
        "nix",
        "perl",
        "php",
        "python",
        "r",
        "regex",
        "regex",
        "rst",
        "rst",
        "ruby",
        "rust",
        "scss",
        "sql",
        "terraform",
        "toml",
        "vim",
        "yaml",
      }
    end,
  },
}
